#!/bin/bash
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 0.1
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 0.3
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 0.5
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 0.8
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 1
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 2
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 5
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 10
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 25
# python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 70 --l1_coeff 100

python scripts/l2_only.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 50 
python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 50 --l1_coeff 0.25
python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 50 --l1_coeff 0.5
python scripts/25_train_jackal.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 50 --l1_coeff 0.75
python scripts/l1_only.py --dataset_config_path jackal_data/different_train_val.yaml --epochs 50 