#!/bin/bash
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-15-51-08.bag save_data_path:=/robodata/dfarkash/patch_images/concrete/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-07-18.bag save_data_path:=/robodata/dfarkash/patch_images/concrete/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-14-57.bag save_data_path:=/robodata/dfarkash/patch_images/grass/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-26-45.bag save_data_path:=/robodata/dfarkash/patch_images/grass/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-35-30.bag save_data_path:=/robodata/dfarkash/patch_images/grass/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-42-53.bag save_data_path:=/robodata/dfarkash/patch_images/pebble/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-16-56-26.bag save_data_path:=/robodata/dfarkash/patch_images/pebble/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-17-09-55.bag save_data_path:=/robodata/dfarkash/patch_images/mulch/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-17-18-46.bag save_data_path:=/robodata/dfarkash/patch_images/mulch/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-17-26-59.bag save_data_path:=/robodata/dfarkash/patch_images/mulch/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-17-33-58.bag save_data_path:=/robodata/dfarkash/patch_images/mulch/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-18-41-00.bag save_data_path:=/robodata/dfarkash/patch_images/speedway/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-18-52-53.bag save_data_path:=/robodata/dfarkash/patch_images/speedway/ visualize:=false
# roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-19-00-56.bag save_data_path:=/robodata/dfarkash/patch_images/brick/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-10/_2022-05-10-19-20-16.bag save_data_path:=/robodata/dfarkash/patch_images/brick/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-12-25-50.bag save_data_path:=/robodata/dfarkash/patch_images/speedway/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-12-35-44.bag save_data_path:=/robodata/dfarkash/patch_images/speedway/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-13-45-01.bag save_data_path:=/robodata/dfarkash/patch_images/rock/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-14-00-41.bag save_data_path:=/robodata/dfarkash/patch_images/rock/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-14-08-59.bag save_data_path:=/robodata/dfarkash/patch_images/multiple/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-14-20-22.bag save_data_path:=/robodata/dfarkash/patch_images/multiple/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-14-36-59.bag save_data_path:=/robodata/dfarkash/patch_images/multiple/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-14-47-47.bag save_data_path:=/robodata/dfarkash/patch_images/multiple/ visualize:=false
roslaunch launch/parse_rosbag.launch rosbag_path:=/robodata/eyang/data/2022-05-11/_2022-05-11-15-03-25.bag save_data_path:=/robodata/dfarkash/patch_images/multiple/ visualize:=false